const BLOCK_HEIGHT = 30;
const BLOCK_WIDTH = 30;
const GAME_SCENE_HEIGHT = 600;
const GAME_SCENE_WIDTH = 360;
const HUD_WIDTH = 140;
const ABOVE_GAP = 2;

export default {
    BLOCK_HEIGHT: BLOCK_HEIGHT,
    BLOCK_WIDTH: BLOCK_WIDTH,
    GAME_SCENE_HEIGHT: GAME_SCENE_HEIGHT,
    GAME_SCENE_WIDTH: GAME_SCENE_WIDTH,
    HUD_WIDTH: HUD_WIDTH,
    ABOVE_GAP: ABOVE_GAP
}